import Testing

@testable import KokoroCoreML

@Suite("Tokenizer")
struct TokenizerTests {
    private func makeTokenizer() throws -> Tokenizer {
        try Tokenizer.loadFromBundle()
    }

    @Test("Encode adds BOS and EOS")
    func encodeAddsBosEos() throws {
        let tok = try makeTokenizer()
        let ids = tok.encode("a")
        #expect(ids.first == Tokenizer.bosId)
        #expect(ids.last == Tokenizer.eosId)
        #expect(ids.count >= 3)  // BOS + at least 1 token + EOS
    }

    @Test("Unknown characters silently dropped")
    func unknownCharsDropped() throws {
        let tok = try makeTokenizer()
        let withEmoji = tok.encode("a🎉b")
        let without = tok.encode("ab")
        #expect(withEmoji == without)
    }

    @Test("Encoded symbol count matches dropped unknown behavior")
    func encodedSymbolCount() throws {
        let tok = try makeTokenizer()
        #expect(tok.encodedSymbolCount("a🎉b") == tok.encode("ab").count - 2)
    }

    @Test("Max length enforced")
    func maxLength() throws {
        let tok = try makeTokenizer()
        let longIPA = String(repeating: "a", count: 1000)
        let ids = tok.encode(longIPA, maxLength: 100)
        #expect(ids.count <= 100)
        #expect(ids.last == Tokenizer.eosId)
    }

    @Test("Empty string produces BOS + EOS only")
    func emptyString() throws {
        let tok = try makeTokenizer()
        let ids = tok.encode("")
        #expect(ids == [Tokenizer.bosId, Tokenizer.eosId])
    }

    // Reference token IDs generated by Kokoro's Python tokenizer:
    //   [0, *[vocab[p] for p in phonemes if p in vocab], 0]

    @Test("hello world matches Python reference")
    func helloWorldReference() throws {
        let tok = try makeTokenizer()
        let ids = tok.encode("hɛlˈoʊ wˈɜːld")
        #expect(ids == [0, 50, 86, 54, 156, 57, 135, 16, 65, 156, 87, 158, 54, 46, 0])
    }

    @Test("quick brown fox matches Python reference")
    func quickBrownFoxReference() throws {
        let tok = try makeTokenizer()
        let ids = tok.encode("ðə kwˈɪk bɹˈaʊn fˈɑːks dʒˈʌmps ˈoʊvɚ ðə lˈeɪzi dˈɑːɡ")
        #expect(
            ids == [
                0, 81, 83, 16, 53, 65, 156, 102, 53, 16, 44, 123, 156, 43, 135, 56, 16, 48, 156,
                69, 158, 53, 61, 16, 46, 147, 156, 138, 55, 58, 61, 16, 156, 57, 135, 64, 85, 16,
                81, 83, 16, 54, 156, 47, 102, 68, 51, 16, 46, 156, 69, 158, 92, 0,
            ])
    }
}
